#驱动类名称
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}
#数据库连接的url
spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/teaching-manager}
#连接数据库的用户名
spring.datasource.username=${DB_USERNAME:root}
#连接数据库的密码
spring.datasource.password=${DB_PASSWORD:123456}

#指定mybatis输出日志到控制台上
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
#开启驼峰命名
mybatis.configuration.map-underscore-to-camel-case=true